import type { Metadata } from "next";
import { H2, P, UL } from "../Prose";

export const metadata: Metadata = { title: "Privacy Policy | ProcurePro" };

const EFFECTIVE_DATE = "26 August 2026";

export default function PrivacyPage() {
  return (
    <article>
      <h1 className="text-3xl font-semibold tracking-tight text-zinc-900 dark:text-zinc-100">Privacy Policy</h1>
      <p className="mt-2 text-sm text-zinc-400 dark:text-zinc-500">Effective {EFFECTIVE_DATE}</p>

      <P>
        This Privacy Policy explains what personal data ProcurePro collects, why, and how it&rsquo;s handled, in line
        with the Nigeria Data Protection Act 2023 and its regulations. It applies to visitors to our site and to
        users of the ProcurePro application.
      </P>

      <H2>1. What we collect</H2>
      <P>Depending on how you interact with ProcurePro, we collect:</P>
      <UL>
        <li><strong>Account data</strong> — name, work email, password (stored hashed, never in plain text), role, and the organization you belong to.</li>
        <li><strong>Procurement data you enter</strong> — purchase requests, vendor records, purchase orders, budgets, invoices, and related documents you or your organization upload.</li>
        <li><strong>Payment-related data</strong> — subscription status and billing history. Card details are entered directly on Paystack&rsquo;s hosted checkout and never touch ProcurePro&rsquo;s servers. Vendor bank account details you enter for vendor payouts are stored to enable transfers and are verified against the receiving bank via Paystack/Flutterwave before use.</li>
        <li><strong>Demo requests</strong> — if you submit the &ldquo;request a demo&rdquo; form, we store your name, work email, company, and the UTM parameters of the link you arrived from, so we know which marketing channel it came from.</li>
        <li><strong>Usage and log data</strong> — basic technical logs (IP address, timestamps) generated by our hosting and security infrastructure, used for abuse prevention (e.g. signup rate limiting) and troubleshooting.</li>
      </UL>

      <H2>2. Cookies</H2>
      <P>
        ProcurePro uses a small number of strictly functional cookies: your signed-in session (via Supabase Auth),
        your light/dark theme preference, and whether your sidebar is collapsed. We do not use advertising or
        third-party analytics/tracking cookies.
      </P>

      <H2>3. How we use your data</H2>
      <UL>
        <li>To provide the core service — running your organization&rsquo;s procurement workflow, approvals, purchase orders, and reporting.</li>
        <li>To process subscription billing and, where you choose to use it, vendor payments.</li>
        <li>To secure the platform — authentication, abuse and fraud prevention, audit logging.</li>
        <li>To respond to support requests and, if you request a demo, to follow up with you.</li>
        <li>To send account and billing notifications (e.g. approval alerts, trial-ending reminders, payment receipts).</li>
      </UL>
      <P>We do not sell your data, and we do not use your procurement or vendor data to train any AI model beyond what&rsquo;s needed to power features you directly use inside your own account.</P>

      <H2>4. Who we share it with</H2>
      <P>We use a small number of service providers (&ldquo;sub-processors&rdquo;) to run ProcurePro, each only for the purpose described:</P>
      <UL>
        <li><strong>Supabase</strong> — database, authentication, and file storage (hosted in the EU).</li>
        <li><strong>Vercel</strong> — application hosting.</li>
        <li><strong>Paystack</strong> and <strong>Flutterwave</strong> — subscription billing and, where used, vendor payment transfers.</li>
        <li><strong>Resend</strong> — transactional email (approval notifications, receipts).</li>
      </UL>
      <P>
        We don&rsquo;t share your data with anyone else, except where required by law or to protect ProcurePro&rsquo;s
        or others&rsquo; legal rights.
      </P>

      <H2>5. Where your data is stored</H2>
      <P>
        Your data is stored on infrastructure located outside Nigeria (in the EU, via our hosting providers). By
        using ProcurePro you consent to this transfer, which is protected by our providers&rsquo; own security and
        data-protection commitments.
      </P>

      <H2>6. Data retention</H2>
      <P>
        We keep your data for as long as your account is active. If you cancel your subscription or your account is
        closed, we retain data for a reasonable period to allow reactivation or export, after which it is deleted or
        anonymized, except where we&rsquo;re required to keep records longer for legal or accounting reasons.
      </P>

      <H2>7. Your rights</H2>
      <P>
        Under the Nigeria Data Protection Act, you can ask us to access, correct, export, or delete the personal data
        we hold about you, or object to certain processing. Organization administrators can access and correct most
        account data directly inside ProcurePro; for anything else, contact us using the details below.
      </P>

      <H2>8. Changes to this policy</H2>
      <P>
        If we make material changes to this policy, we&rsquo;ll update the effective date above and notify account
        administrators where appropriate.
      </P>

      <H2>9. Contact</H2>
      <P>
        For any privacy question or request, contact{" "}
        <a href="mailto:den.kobbis@gmail.com" className="font-medium text-brand-600 hover:text-brand-700 dark:text-brand-400 dark:hover:text-brand-300">
          den.kobbis@gmail.com
        </a>
        .
      </P>
    </article>
  );
}
