-- Generalized version of signup_attempts' pattern, for the two other
-- pre-auth flows that need the same IP-based rate limiting: login and
-- password-reset requests. Kept as one shared table (not three) since the
-- mechanics are identical; signup_attempts itself is left untouched since
-- it already works and touching it isn't needed for this.
--
-- Same reasoning as signup_attempts_select/_insert: this must be readable
-- and writable with no session at all (a login/reset attempt happens
-- before auth succeeds), so RLS can't scope it by org/user. The only data
-- exposed is an IP address and a timestamp -- low-sensitivity by design.

create table auth_attempts (
  id bigint generated by default as identity primary key,
  ip_address text not null,
  attempt_type text not null check (attempt_type in ('login', 'password_reset')),
  created_at timestamptz not null default now()
);
create index auth_attempts_ip_type_idx on auth_attempts (ip_address, attempt_type, created_at);

alter table auth_attempts enable row level security;
create policy auth_attempts_insert on auth_attempts for insert with check (true);
create policy auth_attempts_select on auth_attempts for select using (true);
